const LOGIN = "LOGIN";

const JOIN_GAME_REQUEST = "JOIN_GAME_REQUEST";
const JOIN_GAME_SUCCESS = "JOIN_GAME_SUCCESS";
const JOIN_GAME_FAILURE = "JOIN_GAME_FAILURE";
const START_GAME = "START_GAME";
const MOVE_PIECE = "MOVE_PIECE";
const TOGGLE_TURN = "TOGGLE_TURN";
